name: Run CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./hellosociallife
      
      - name: Run type check
        run: npm run typecheck
        working-directory: ./hellosociallife


      - name: Run tests
        run: npm run test
        working-directory: ./hellosociallife


  coverage_support:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        working-directory: ./hellosociallife 
      
      - name: Run build
        run: npm run test:coverage
        working-directory: ./hellosociallife 

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ./hellosociallife
